name: Development
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    if: ${{ github.repository == 'matterbridge-org/matterbridge' }}
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          # Only compare with previous commit when pushing,
          # and with base branch when in PR.
          only-new-issues: true
          args: --build-tags=goolm
      - name: golangci-lint (entire codebase)
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: --build-tags=goolm --config=.golangci-incremental.yaml
  lint_personal_fork:
    if: ${{ github.repository != 'matterbridge-org/matterbridge' }}
    name: golangci-lint (personal fork branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: "git remote add upstream https://github.com/matterbridge-org/matterbridge"
      # - run: "git fetch upstream master"
      # - run: "git branch __ci_upstream_master FETCH_HEAD"
      - run: "git fetch upstream master"
      # We only compare with the most recent common ancestor. Otherwise, code that was removed
      # upstream but does not conflict (and therefore will not appear in Github PR UI)
      #  will trigger new linter errors downstream (false positive).
      # - run: echo "COMMON_ANCESTOR=$(git merge-base __ci_upstream_master ${{ github.ref }})" >> $GITHUB_ENV
      # - run: echo "COMMON_ANCESTOR=$(git merge-base __ci_upstream_master ${{ github.ref }})"
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Maybe only-new-issues works with a simple unshallow?
          # only-new-issues: true
          version: v2.1
          skip-cache: true
          args: --build-tags=goolm --new-from-rev=upstream/master
          # Compare to upstream's master branch.
          # It looks like Github Actions partial clones don't really like comparing
          # with previous commit overwritten by a force push, which in any case does
          # not really make sense when working on a feature branch.
          # args: >-
          #   --build-tags=goolm --new-from-rev=${{ env.COMMON_ANCESTOR }}
  test:
    strategy:
      matrix:
        # Test on latest release and v1.24
        go-version: [1.24.x, stable]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v5
      - name: go fmt ./... (go version ${{ matrix.go-version }})
        run: test -z "$(go fmt ./...)"
      - name: go test -tags goolm ./... (go version ${{ matrix.go-version }})
        run: go test -tags goolm ./...
  build-upload:
    # Dont build artifacts for downstream branches not tracked by a PR
    if: ${{ github.event_name == 'pull_request' || github.repository == 'matterbridge-org/matterbridge' }}
    # Uploading artifacts only if lint/test succeeded
    needs: [ "lint", "test" ]
    strategy:
      matrix:
        arch: [amd64]
        platform:
          - name: linux
            goos: linux
          - name: windows
            goos: windows
          - name: mac
            goos: darwin
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build/upload matterbridge for ${{ matrix.platform.goos }}-${{ matrix.arch }}
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.platform.goos }} GOARCH=${{ matrix.arch }} go build -tags goolm -ldflags "-s -X github.com/matterbridge-org/matterbridge/version.GitHash=$(git log --pretty=format:'%h' -n 1)" -o matterbridge
      - name: Upload matterbridge-${{ matrix.name }}-${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: matterbridge-${{ matrix.platform.goos }}-${{ matrix.arch }}
          path: matterbridge
