name: Development
on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
permissions:
  contents: read
  pull-requests: read
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.24.x
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          # Only compare with previous commit when pushing,
          # and with base branch when in PR.
          only-new-issues: true
  test:
    strategy:
      matrix:
        # Test on latest release and v1.24
        go-version: [1.24.x, stable]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v5
      - name: go fmt ./... (go version ${{ matrix.go-version }})
        run: test -z "$(go fmt ./...)"
      - name: go test ./... (go version ${{ matrix.go-version }})
        run: go test ./...
  build-upload:
    # Uploading artifacts only if lint/test succeeded
    needs: [ "lint", "test" ]
    strategy:
      matrix:
        arch: [amd64]
        platform:
          - name: linux
            goos: linux
          - name: windows
            goos: windows
          - name: mac
            goos: darwin
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build/upload matterbridge for ${{ matrix.platform.goos }}-${{ matrix.arch }}
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.platform.goos }} GOARCH=${{ matrix.arch }} go build -ldflags "-s -X github.com/42wim/matterbridge/version.GitHash=$(git log --pretty=format:'%h' -n 1)" -o matterbridge
      - name: Upload matterbridge-${{ matrix.name }}-${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: matterbridge-${{ matrix.platform.goos }}-${{ matrix.arch }}
          path: matterbridge
